#test 
logging:
  level:
    tk.mybatis: DEBUG
    com.teradata.openpai.test: DEBUG

spring:
  application:
    name: td-openapi-microservice-admin
  datasource:
    name: test
    url: jdbc:postgresql://localhost:5432/openapi
    username: iop
    password: iop
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.teradata.openpai.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml

eureka:
#  instance:
#     prefer-ip-address: true
#     ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://admin:123@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      status-page-url-path: /info
      health-check-url-path: /health
server:
  port: 7771



















